menu:
    首页: /
    全部文章: /archives/
    镜像站: https://mirrors.shu.edu.cn
    上大助手: https://www.shuhelper.cn
    上大导航: https://shuer.link

widgets:
- category
- tag
- tagcloud
- archive

# count
show_count: true
favicon: /images/favicon.ico
logo: /images/logo.png

# Comment
changyan: shuosc
yungentie: 
disqus:
duoshuo: 


# Analytics
# google-analytics:
ga: UA-113238974-3

# Copyright Infomation
startyear: 2016

