stages:
- deploy
deploy:
  stage: deploy
  script:
    - export PATH=$PATH:/home/asc/.nvm/versions/node/v9.3.0/bin
    - npm config set registry https://registry.npm.taobao.org
    - npm install
    - hexo generate
    - rm -rf /var/www/blog.shuosc.org/*
    - cp source/img public/img -R
    - cp public/* /var/www/blog.shuosc.org -R

  only:
    - master
  tags:
    - shell